### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

### ISSUE THREAD

**Issue by abhinavrawat27** [newbiehyz/hand_jetsonnano#1]
Hi

I am trying to run your project on a custom build Jetson Xavier device. My goal is to just run the inference and no led interface. When running the detect.py, I am getting below error:

	[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +346, GPU +0, now: CPU 408, GPU 3664 (MiB)
	[TensorRT] INFO: Loaded engine size: 7 MB
	[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 415 MiB, GPU 3671 MiB
	[TensorRT] ERROR: 6: The engine plan file is generated on an incompatible device, expecting compute 7.2 got compute 5.3, please rebuild.
	[TensorRT] ERROR: 4: [runtime.cpp::deserializeCudaEngine::76] Error Code 4: Internal Error (Engine deserialization failed.)
	Traceback (most recent call last):
	  File "detect.py", line 396, in <module>
		main_camera()
	  File "detect.py", line 383, in main_camera
		yolov5_wrapper = YoLov5TRT(engine_file_path)
	  File "detect.py", line 99, in __init__
		context = engine.create_execution_context()
	AttributeError: 'NoneType' object has no attribute 'create_execution_context'
	delete object to release memory
	-------------------------------------------------------------------
	PyCUDA ERROR: The context stack was not empty upon module cleanup.
	-------------------------------------------------------------------
	A context was still active when the context stack was being
	cleaned up. At this point in our execution, CUDA may already
	have been deinitialized, so there is no way we can finish
	cleanly. The program will be aborted now.
	Use Context.pop() to avoid this problem.
	-------------------------------------------------------------------
	Aborted (core dumped)

I know this error says that I need to rebuild the engine file. Can you help me in that, how can I rebuild it?

**Comment by Muammer06** [comment]
what version jetpack are you using? try numpy 1.19.4 for jetson. 1.19.5 was getting core dumped error all time for me.
